<a href="https://colab.research.google.com/github/Keerthanabs1326/assesment01/blob/main/weekly_assessment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. What is the difference between the `is` operator and the `==` operator? Give one example wheretwo variables return True for `==` but False for `is`.

=> 'is' operator is used to chech whether the object is in the exact memory or not. Whereas '==' operator is used to compare the object to see whether they are equal or not.

Q2. Classify the following as Mutable or Immutable: list, tuple, set, dict, str, int, float, bool,frozenset. Explain in one line WHY immutability matters in real code.

=> Mutable types :- list, set, dict
   Immuatable types :- tuple, string, int, float, bool, frozenset.

   Immutability matters because it prevents accidental bugs, makes code safe when running multiple tasks at once, and allows these values to be used as reliable keys in dictionaries.

Q3. Predict the output of `print(0.1 + 0.2 == 0.3)`. Then explain WHY this happens. (Hint: it is not aPython bug.)

=> Predicted value : 0.3
   Actual output: False

   This happens becuase computers handle floating-point numbers. Computers store numbers in binary format using 0's and 1's. fractions like 0.1 and 0.2 become repeating, infinite fractions in binary. As it is not possible to store infinite fractions in binary format it should roud up to a nearest value so that it can fit to a standard memory.
   
   ">>> 0.1 + 0.2 = 0.30000000000000004"
    
    Because 0.30000000000000004 is not exactly equal to 0.3, the comparison evaluates to False.


Q4. Both list and tuple can store ordered collections. Give 3 concrete situations where you wouldCHOOSE a tuple over a list, and explain the reasoning behind each.

=> Lists and tuples can store ordered collections. Tuples are immutable while lists are mutable.

3 situations where I would choose tuple over a list:

1) When I write a function that needs to return more than one piece of data, such as a user's first name, last name, and email address simultaneously. Because returning data as a tuple represents a single, cohesive record where the data structure is fixed. It allows for clean syntax through tuple unpacking (e.g., first, last, email = get_user_data()), making the code highly readable and efficient.

2)  When I am storing data that must never change during the program's execution, such as geographic coordinates, RGB color values (255, 255, 255), or a configuration setting like (HOST, PORT). Because using a tuple acts as a write-protection mechanism. It signals to other developers that the data is a constant and prevents accidental overwrites, deletions, or modifications elsewhere in the code.

3) When I need to use a composite collection of items (like a coordinate pair (x, y)) as a key in a dictionary or as an element in a set. Because Python requires dictionary keys and set elements to be hashable (unchanging), lists can be modified, they are unhashable and will throw a TypeError. Tuples are immutable, making them hashable and perfectly suited for this purpose.

Q5. Why is dictionary lookup O(1) on average while searching for a value in a list using `in` is O(n)?Explain in plain English without using the word "hash" - then explain it again WITH the word "hash".

 => Dictionary lookup takes \(O(1)\) constant time on average, while searching a list using in takes \(O(n)\) linear time because lists require checking elements one by one from start to finish, whereas dictionaries compute the exact memory location of a key instantly.

 Without Using the Forbidden Word
 List Search (O(n)): Like walking down a single-file line of people and asking each person one by one if their name is "Sam" until you find them.Dictionary Lookup (O(1)): Like using a directory in an apartment lobby that instantly tells you "Sam is in Room 402," letting you walk straight to that room in one step.

 With the Word "Hash"
 List Search (O(n)): Items are stored sequentially, so the in operator must perform a linear scan through the entire list to find a match.Dictionary Lookup (O(1)): The dictionary passes the key through a hash function, which acts as a mathematical formula to instantly calculate the exact index in the underlying hash table where the value lives.

Q6. What is the difference between `range()` and `numpy.arange()`? Mention at least 3 differences,one of them should involve floats

=> range() is a built-in Python function that only supports integer steps, returns a lazy range object, and consumes minimal memory.numpy.arange() is a NumPy library function that supports float steps (e.g., 0.5), returns an eager N-dimensional array, and occupies larger sequential memory.While range() is optimized for loop iterations in pure Python, numpy.arange() is designed for fast vectorised math and numeric operations.

Q7. What is the difference between `list.append(x)`, `list.extend(x)`, and `list.insert(i, x)`? For each,show what happens when `x = [4, 5]` is added to `a = [1, 2, 3]`.

=> append() adds one item at the end, extend() merges all items at the end, and insert() adds one item at a specific position.Given a = [1, 2, 3] and x = [4, 5]:a.append(x): Results in [1, 2, 3, [4, 5]] by adding the nested list.a.extend(x): Results in [1, 2, 3, 4, 5] by flattening the items.a.insert(1, x): Results in [1, [4, 5], 2, 3] by inserting the nested list at index 1.

Q8. What does this line do, and what are the values of a, b, c after execution?a, *b, c = [10, 20, 30, 40, 50]Now, what happens if you write: `a, *b, c = [10, 20]` ? And `a, *b, c = [10]` ?

=> This line uses iterable unpacking to assign the first element to a, the last element to c, and packs all remaining middle elements into a list for b.

Here are the results for each case:

a, *b, c = [10, 20, 30, 40, 50]
a = 10
b = [20, 30, 40]
c = 50
a, *b, c = [10, 20]
a = 10
b = []

(an empty list because no elements are left over)
c = 20
a, *b, c = [10]
Result: ValueError: not enough values to unpack (Python requires at least two elements to satisfy a and c).

Q9. Explain the difference between `/`, `//`, `%`, and `**` operators in Python. For each, give theoutput of the operation when applied to (-7, 2).

=> Operator Differences & Output for (-7, 2)/ (True Division): Returns float quotient. -7 / 2 = -3.5// (Floor Division): Rounds quotient down towards $-\infty$. -7 // 2 = -4% (Modulo): Returns remainder where $r = a - (b \times (a // b))$. -7 % 2 = 1** (Exponentiation): Raises base to power. (-7) ** 2 = 49

Q10. Why is NumPy significantly faster than Python lists for numerical operations? Give 3 reasons, atleast one should mention memory layout.

=> Contiguous Memory Layout: NumPy arrays store homogeneous data in contiguous memory blocks (cache-friendly), whereas Python lists store pointers to scattered objects.

Homogeneous Data (No Type Overhead): Fixed C types eliminate dynamic type checking and object boxing/unboxing during iterations.

C Implementation & Vectorization: Operations execute compiled SIMD C/Fortran routines directly, bypassing Python's loop overhead and GIL.

Q11. Predict the output. Why does the second line behave differently from the first?matrix1 = [[0] * 3 for _ in range(3)]matrix2 = [[0] * 3] * 3matrix1[0][0] = 99matrix2[0][0] = 99print(matrix1)print(matrix2)

=> Predicted Output:
[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]
Why: List comprehension in matrix1 creates 3 independent list objects. matrix2 uses * 3, which creates 3 references pointing to the exact same list in memory.

Q12. Predict the output:x = [1, 2, 3]y = xx = x + [4]print("x =", x)print("y =", y)a = [1, 2, 3]b = aa += [4]print("a =", a)print("b =", b)Now answer: Why do `x = x + [4]` and `a += [4]` behave differently?

=> Predicted Output:
x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]
Why: x + [4] creates a brand-new list object and rebinds x, leaving y unchanged. a += [4] calls list.__iadd__(), mutating the existing list in-place, which reflects in both a and b.

Q13. Predict the output. What is the value of `i` after the loop ends, and why?for i in range(5):passprint(i)for j in range(0):passprint(j) # think before you write

=> Predicted Output: 4
NameError: name 'j' is not defined
Why: In Python, loop variables persist in scope after the loop terminates (i = 4). Since range(0) is empty, the second loop never runs, so j is never initialized.

Q14. Predict the output of each print statement. Then state which lines will raise an error (if any).print("10" + "20")print(10 + 20)print("10" * 3)print(10 * "3")
THE UNLOX ACADEMY | Data Science Data Analytics Week 1 - Master AssignmentThe Unlox Academy Page 6 of 16print("10" + 20)print(int("10") + 20)

=> Predicted Output:print("10" + "20") -> 1020p
rint(10 + 20) -> 30
print("10" * 3) -> 101010
print(10 * "3") -> 3333333333
print("10" + 20) -> Raises TypeError (cannot concatenate str and int)
print(int("10") + 20) -> 30

Q15. Predict the output. Then explain Python's short-circuit evaluation in one line.print(0 or 5)print(5 or 0)print(None or "hello")print(0 and 5)print(5 and 10)print([] or "default")print([0] or "default") # careful!

=> Predicted Output:

5

5

hello

0

10

default

[0]

Python evaluates logical expressions left-to-right and halts evaluation as soon as the outcome is determined, returning the operand itself rather than a boolean.

Q16. Swap two numbers WITHOUT using a third variable. Implement 3 different methods: (a) usingarithmetic, (b) using XOR (`^`), (c) using tuple unpacking. Compare which is most Pythonic.

=> a, b = 10, 20
1) Arithmetic

a = a + b; b = a - b; a = a - b

2) XOR

a = a ^ b; b = a ^ b; a = a ^ b

3) Tuple upacking (most safe and reliable)
a, b = b, a

Q17. Swiggy Order Calculator. Take item price and quantity as input. Compute total = price ×quantity. Add 18% GST. Add ₹40 delivery charge if total (before delivery) is below ₹500, else deliveryis FREE. Print all components separately and final amount in this format:Subtotal: ₹450.00GST (18%): ₹81.00Delivery: ₹40.00------------------------Total: ₹571.00

=>

In [7]:
price, qty = float(input()), int(input())
subtotal = price * qty
gst = subtotal * 0.18
delivery = 0.0 if subtotal >= 500 else 40.0
total = subtotal + gst + delivery

print(f"Subtotal:   ₹{subtotal:.2f}\nGST (18%):  ₹{gst:.2f}\nDelivery:   ₹{delivery:.2f}\n------------------------\nTotal:      ₹{total:.2f}")

250
2
Subtotal:   ₹500.00
GST (18%):  ₹90.00
Delivery:   ₹0.00
------------------------
Total:      ₹590.00


Q18. Temperature converter. Ask user for a value and unit (C or F). Convert and print result roundedto 2 decimal places. Handle invalid unit input gracefully (print an error message, do NOT crash).

In [8]:
val = float(input("Value: "))
unit = input("Unit (C/F): ").strip().upper()

if unit == "C":
    print(f"{(val * 9/5) + 32:.2f}°F")
elif unit == "F":
    print(f"{(val - 32) * 5/9:.2f}°C")
else:
    print("Error: Invalid unit. Use 'C' or 'F'.")

Value: 25
Unit (C/F): C
77.00°F


Q19. Take a 4-digit number as input. Print the sum of its digits – WITHOUT converting it to a string.(Use only integer arithmetic: //, %.)

In [10]:
n = int(input())
total = 0
while n > 0:
    total += n % 10
    n //= 10
print(total)

1234
10


Q20. Smart input parser. Take a single input from the user. Detect what type it is  try int first, thenfloat, else treat as string. Print the value AND its detected type. Example: input "42" → int 42, input"3.14" → float 3.14, input "hello" → str hello.

In [11]:
raw = input()
try:
    val = int(raw)
    print(val, type(val))
except ValueError:
    try:
        val = float(raw)
        print(val, type(val))
    except ValueError:
        print(raw, type(raw))

25
25 <class 'int'>


Q21. Indian Income Tax Calculator (New Regime, FY 2024–25). Take annual income as input.Compute tax using these slabs:Up to ₹3,00,000 : Nil₹3,00,001 – ₹7,00,000 : 5%₹7,00,001 – ₹10,00,000 : 10%₹10,00,001 – ₹12,00,000 : 15%₹12,00,001 – ₹15,00,000 : 20%Above ₹15,00,000 : 30%Tax must be computed slab-wise, NOT flat. Example: income ₹8,00,000 → 0 on first 3L + 5% on next 4L + 10% onlast 1L = ₹20,000 + ₹10,000 = ₹30,000. Print breakdown clearly.

In [13]:
inc = float(input())
slabs = [(300000, 0.0), (400000, 0.05), (300000, 0.10), (200000, 0.15), (300000, 0.20)]
tax, rem = 0, inc

for cap, rate in slabs:
    taxable = min(rem, cap)
    tax += taxable * rate
    rem -= taxable
    if rem <= 0: break
if rem > 0:
    tax += rem * 0.30

print(f"Total Tax: ₹{tax:.2f}")

400000
Total Tax: ₹5000.00


Q22. Validate Indian PAN card format WITHOUT using regex. Format: AAAAA9999A, first 5 areuppercase letters, next 4 are digits, last 1 is an uppercase letter. Total length = 10. Take input andprint "Valid PAN" or "Invalid PAN — <reason>" where reason explains exactly what's wrong.

In [14]:
pan = input().strip()
if len(pan) != 10:
    print("Invalid PAN — Length must be exactly 10")
elif not (pan[:5].isalpha() and pan[:5].isupper()):
    print("Invalid PAN — First 5 characters must be uppercase letters")
elif not pan[5:9].isdigit():
    print("Invalid PAN — Characters 6 to 9 must be digits")
elif not (pan[9].isalpha() and pan[9].isupper()):
    print("Invalid PAN — Last character must be an uppercase letter")
else:
    print("Valid PAN")

ABCDE1234F
Valid PAN


Q23. Bengaluru BESCOM Electricity Bill (LT-2 Residential). Take units consumed as input. Charges:0 – 50 units : ₹4.10 per unit51 – 100 units : ₹5.55 per unit101 – 200 units : ₹7.10 per unitAbove 200 units : ₹8.15 per unitAdd fixed charge: ₹110. Add 6% government tax on (energy charges + fixed charge). Print itemized bill.

In [15]:
units = float(input())
rates = [(50, 4.10), (50, 5.55), (100, 7.10)]
energy, rem = 0, units

for limit, rate in rates:
    u = min(rem, limit)
    energy += u * rate
    rem -= u
    if rem <= 0: break
if rem > 0:
    energy += rem * 8.15

sub = energy + 110.0
tax = sub * 0.06
print(f"Energy: ₹{energy:.2f} | Fixed: ₹110.00 | Tax: ₹{tax:.2f} | Total: ₹{sub + tax:.2f}")

25
Energy: ₹102.50 | Fixed: ₹110.00 | Tax: ₹12.75 | Total: ₹225.25


Q24. Cricket Strike Rate Classifier. Take runs scored and balls faced. Compute strike rate =(runs/balls) × 100. Classify:SR > 150 → Explosive (T20 finisher)100 < SR ≤ 150 → Aggressive (Top order T20)75 ≤ SR ≤ 100 → Steady (ODI anchor)SR < 75 → Defensive (Test match)Edge case: handle balls = 0 (do not crash, print message instead).

In [16]:
runs, balls = int(input()), int(input())
if balls == 0:
    print("Balls faced cannot be zero.")
else:
    sr = (runs / balls) * 100
    cat = "Explosive" if sr > 150 else "Aggressive" if sr > 100 else "Steady" if sr >= 75 else "Defensive"
    print(f"SR: {sr:.2f} — {cat}")

200
100
SR: 200.00 — Explosive


Q25. BMI Calculator (Indian standards). Take weight (kg) and height (cm). Compute BMI = weight /(height_in_meters)². Classify using Indian (not WHO) BMI categories:BMI < 18.5 → Underweight18.5 – 22.9 → Normal (Indian range — narrower than WHO)23.0 – 24.9 → Overweight25.0 – 29.9 → Obese Class IBMI ≥ 30 → Obese Class II

In [17]:
w, h_cm = float(input()), float(input())
bmi = w / ((h_cm / 100) ** 2)
cat = "Underweight" if bmi < 18.5 else "Normal" if bmi <= 22.9 else "Overweight" if bmi <= 24.9 else "Obese Class I" if bmi <= 29.9 else "Obese Class II"
print(f"BMI: {bmi:.2f} — {cat}")

50
170
BMI: 17.30 — Underweight


Q26. Print this pattern for N = 5:

1

1 2

1 2 3

1 2 3 4

1 2 3 4 5

In [19]:
n = int(input())
for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


Q27. Print this number diamond for N = 5 (the digits go up to N in the middle row):

1

1 2 1

1 2 3 2 1

1 2 3 4 3 2 1

1 2 3 4 5 4 3 2 1

1 2 3 4 3 2 1

1 2 3 2 1

1 2 1

1

In [20]:
n = int(input())
for i in list(range(1, n + 1)) + list(range(n - 1, 0, -1)):
    for j in range(1, i + 1):
        print(j, end=" ")
    for j in range(i - 1, 0, -1):
        print(j, end=" ")
    print()

5
1 
1 2 1 
1 2 3 2 1 
1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
1 2 3 4 3 2 1 
1 2 3 2 1 
1 2 1 
1 


Q28. Print a hollow square of size N (only the border is *, inside is blank). For N = 5:

In [21]:
n = int(input())
for i in range(n):
    for j in range(n):
        print("*" if i in (0, n - 1) or j in (0, n - 1) else " ", end=" ")
    print()

5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


Q29. Print the first 5 rows of Pascal's Triangle:

1

1 1

1 2 1

1 3 3 1

1 4 6 4 1

In [22]:
for i in range(5):
    val = 1
    for j in range(i + 1):
        print(val, end=" ")
        val = val * (i - j) // (j + 1)
    print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


Q30. Print this character pattern for N = 5 – letters go up to the N-th alphabet:AA BA B CA B C DA B C D E

In [23]:
n = int(input())
for i in range(n):
    for j in range(i + 1):
        print(chr(65 + j), end=" ")
    print()

5
A 
A B 
A B C 
A B C D 
A B C D E 


Q31. Find all Armstrong numbers between 1 and 9999. (An n-digit number is Armstrong if the sum ofits digits each raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.) Print themin a clean comma-separated list with a count at the end.

In [24]:
res = []
for i in range(1, 10000):
    t, s, d = i, 0, len(str(i))
    while t > 0:
        s += (t % 10) ** d
        t //= 10
    if s == i:
        res.append(i)
print(", ".join(map(str, res)), f"\nCount: {len(res)}")

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474 
Count: 16


Q32. Take N as input. Print the first N terms of the Fibonacci series. Also compute and print the SUMof those N terms. Do NOT use recursion. Edge case: N = 0 should print nothing, sum = 0. N = 1 shouldprint just 0

In [25]:
n = int(input())
a, b, total = 0, 1, 0
for _ in range(n):
    print(a, end=" ")
    total += a
    a, b = b, a + b
print(f"\nSum: {total}")

10
0 1 1 2 3 5 8 13 21 34 
Sum: 88


Q33. Prime check, optimized. Take a number N. Check if it is prime by iterating only up to √N. Then,print the SUM of all primes between 2 and N (inclusive). Do not use any library.

In [26]:
n = int(input())
def is_prime(x):
    if x < 2: return False
    for i in range(2, int(x ** 0.5) + 1):
        if x % i == 0: return False
    return True

print("Prime" if is_prime(n) else "Not Prime")
print("Sum of primes:", sum(x for x in range(2, n + 1) if is_prime(x)))

10
Not Prime
Sum of primes: 17


Q34. Take a number as input. Reverse it WITHOUT converting to string. Then check if the original andreversed are equal (palindrome). Handle negative numbers, they should be considered NOTpalindrome (because of the minus sign). Examples: 121 → palindrome, 123 → not palindrome, -121→ not palindrome.

In [27]:
n = int(input())
if n < 0:
    print("Not palindrome")
else:
    temp, rev = n, 0
    while temp > 0:
        rev = rev * 10 + temp % 10
        temp //= 10
    print(f"Reversed: {rev} | {'Palindrome' if rev == n else 'Not palindrome'}")

1234321
Reversed: 1234321 | Palindrome


Q35. Take two positive integers. Compute their HCF (Highest Common Factor) using Euclideanalgorithm with a `while` loop. Then compute LCM using the relation: HCF × LCM = a × b. Do not usemath.gcd.

In [28]:
a, b = int(input()), int(input())
x, y = a, b
while y:
    x, y = y, x % y
hcf = x
lcm = (a * b) // hcf
print(f"HCF: {hcf}, LCM: {lcm}")

7
13
HCF: 1, LCM: 91


Q36. String scanner, single pass. Take a sentence (e.g., a Swiggy review like "Order came on time,food was hot, packaging 10/10!"). In ONE pass through the string, count: total characters, totalwords, vowels (a, e, i, o, u - case-insensitive), consonants, digits, spaces, and special characters. Printall counts.

In [29]:
s = input()
c_len = len(s)
words = vowels = cons = digits = spaces = specials = 0
in_word = False

for ch in s:
    if ch.isspace():
        spaces += 1
        in_word = False
    else:
        if not in_word:
            words += 1
            in_word = True
        if ch.lower() in "aeiou":
            vowels += 1
        elif ch.isalpha():
            cons += 1
        elif ch.isdigit():
            digits += 1
        else:
            specials += 1

print(f"Chars: {c_len}, Words: {words}, Vowels: {vowels}, Consonants: {cons}, Digits: {digits}, Spaces: {spaces}, Special: {specials}")

Hello123
Chars: 8, Words: 1, Vowels: 2, Consonants: 3, Digits: 3, Spaces: 0, Special: 0


Q37. Take 10 student marks (out of 100) as input, space-separated on one line, parse with split() and
map(). Without using sort() or sorted(), find: (a) maximum, (b) minimum, (c) average, (d) count of
students above average, (e) the SECOND highest mark.

In [31]:
marks = list(map(int, input().split()))
mx = mn = s_max = marks[0]
total = 0

for m in marks:
    if m > mx:
        s_max = mx
        mx = m
    elif m > s_max and m != mx:
        s_max = m
    if m < mn: mn = m
    total += m

avg = total / len(marks)
above_avg = sum(1 for m in marks if m > avg)
print(f"Max: {mx}, Min: {mn}, Avg: {avg:.2f}, Above Avg: {above_avg}, Second Max: {s_max}")

10 20 30 40 50
Max: 50, Min: 10, Avg: 30.00, Above Avg: 2, Second Max: 40


Q38. Word Frequency Analyzer for Swiggy reviews. Take a review sentence. Find the frequency of
each word (case-insensitive, "Food" and "food" should be counted together). Print words sorted by
frequency in descending order. Also print the MOST frequent word and its count. Use a dict.

In [32]:
words = input().lower().split()
freq = {}
for w in words:
    freq[w] = freq.get(w, 0) + 1

sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)
print("Frequencies:", sorted_freq)
print("Most frequent:", sorted_freq[0])

apple banana apple orange banana apple
Frequencies: [('apple', 3), ('banana', 2), ('orange', 1)]
Most frequent: ('apple', 3)


Q39. Indian States CRUD. Pre-populate a dict with 5 Indian states and their capitals (e.g., Karnataka
→ Bengaluru, Maharashtra → Mumbai). Then build a menu-driven program:
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit
Use a while loop. Loop until user chooses option 6.

In [34]:
states = {"Karnataka": "Bengaluru", "Maharashtra": "Mumbai", "Tamil Nadu": "Chennai", "Telangana": "Hyderabad", "Kerala": "Thiruvananthapuram"}

while True:
    ch = input("1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit: ")
    if ch == "1" or ch == "2":
        states[input("State: ")] = input("Capital: ")
    elif ch == "3":
        states.pop(input("State: "), None)
    elif ch == "4":
        print(states.get(input("State: "), "Not found"))
    elif ch == "5":
        for k in sorted(states): print(f"{k} -> {states[k]}")
    elif ch == "6":
        break

1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit: 4
State: Karnataka
Bengaluru
1.Add 2.Update 3.Delete 4.Search 5.Display 6.Exit: 6


Q40. Set Operations. Students in Section A know languages = {Python, Java, C++, SQL}. Students in
Section B know = {Java, JavaScript, Python, Go, SQL}. Using ONLY set operations, find:
(a) Languages known by BOTH sections
(b) Languages known ONLY by Section A
(c) Languages known ONLY by Section B
(d) Total unique languages across both sections
(e) Languages exclusive to one section but not both (symmetric difference)

In [35]:
A = {"Python", "Java", "C++", "SQL"}
B = {"Java", "JavaScript", "Python", "Go", "SQL"}

print("Both:", A & B)
print("Only A:", A - B)
print("Only B:", B - A)
print("Unique total:", A | B)
print("Exclusive to one:", A ^ B)

Both: {'Java', 'Python', 'SQL'}
Only A: {'C++'}
Only B: {'Go', 'JavaScript'}
Unique total: {'Java', 'C++', 'JavaScript', 'SQL', 'Python', 'Go'}
Exclusive to one: {'Go', 'C++', 'JavaScript'}


Q41. TCS stock prices for a week stored as a tuple: `prices = (3845, 3902, 3878, 3955, 4012, 3998,
4055)` (Mon to Sun in ₹). Find: (a) maximum price and which day, (b) minimum price and which day,
(c) average, (d) biggest single-day gain (and between which days), (e) total volatility = sum of
absolute day-to-day price changes.

In [36]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

mx_d = days[prices.index(max(prices))]
mn_d = days[prices.index(min(prices))]
diffs = [prices[i+1] - prices[i] for i in range(len(prices)-1)]
max_gain_idx = diffs.index(max(diffs))

print(f"Max: {max(prices)} ({mx_d}), Min: {min(prices)} ({mn_d}), Avg: {sum(prices)/len(prices):.2f}")
print(f"Biggest Gain: {max(diffs)} ({days[max_gain_idx]} to {days[max_gain_idx+1]})")
print(f"Volatility: {sum(abs(d) for d in diffs)}")

Max: 4055 (Sun), Min: 3845 (Mon), Avg: 3949.29
Biggest Gain: 77 (Wed to Thu)
Volatility: 286


Q42. Given a list of 20 integers (you generate or hardcode them, some duplicates), produce: (a) the
set of unique numbers, (b) the list of numbers appearing more than once, (c) the list of numbers
appearing EXACTLY once. Do this WITHOUT importing Counter or any other library.

In [37]:
nums = [4, 2, 9, 4, 1, 9, 5, 3, 2, 7, 8, 5, 0, 6, 7, 8, 1, 10, 11, 4]
counts = {}
for n in nums: counts[n] = counts.get(n, 0) + 1

unique_set = set(nums)
duplicates = [k for k, v in counts.items() if v > 1]
exactly_once = [k for k, v in counts.items() if v == 1]
print(unique_set, duplicates, exactly_once)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} [4, 2, 9, 1, 5, 7, 8] [3, 0, 6, 10, 11]


Q43. Smart Palindrome Checker. Take a sentence as input. Check if it is a palindrome IGNORING:
case, spaces, and all special characters (punctuation). Examples that should return TRUE: "A man, a
plan, a canal: Panama", "Race car", "No 'x' in Nixon". Hint: build a cleaned version of the string first.

In [38]:
s = input()
clean = [ch.lower() for ch in s if ch.isalnum()]
print(clean == clean[::-1])

hello
False


Q44. Manual Title Case. Take a sentence (e.g., "hello world from bengaluru"). Capitalize the first
letter of EACH word, but do NOT use .title() or .capitalize(). Use only .upper() / .lower() and string
indexing. Output: "Hello World From Bengaluru".

In [39]:
s = input()
res = []
for w in s.split():
    res.append(w[0].upper() + w[1:].lower() if w else "")
print(" ".join(res))

hello world python
Hello World Python


Q45. Caesar Cipher Encryptor. Take a message and a shift value N as input. Encrypt by shifting each
letter forward by N positions in the alphabet (wrapping around, Z + 1 = A). Preserve case. Keep digits,
spaces, and special characters UNCHANGED. Example: "Hello, India!" with shift 3 → "Khoor, Lqgld!"

In [40]:
msg, n = input("Message: "), int(input("Shift: "))
out = []
for ch in msg:
    if ch.isupper():
        out.append(chr((ord(ch) - 65 + n) % 26 + 65))
    elif ch.islower():
        out.append(chr((ord(ch) - 97 + n) % 26 + 97))
    else:
        out.append(ch)
print("".join(out))

Message: Hello 
Shift: 3
Khoor 


Q46. Write a function `calculate_gst(amount, gst_rate=18, gst_inclusive=False)`:
- If gst_inclusive=False: amount is base, add GST on top
- If gst_inclusive=True: amount already includes GST, extract it
- Return a tuple: (base_amount, gst_amount, total_amount)
- All values rounded to 2 decimals
Test cases:
 calculate_gst(1000) → (1000.00, 180.00, 1180.00)
 calculate_gst(1180, gst_inclusive=True) → (1000.00, 180.00, 1180.00)
 calculate_gst(500, gst_rate=5) → (500.00, 25.00, 525.00)

In [41]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        base = amount / (1 + gst_rate / 100)
        gst = amount - base
        return round(base, 2), round(gst, 2), round(amount, 2)
    gst = amount * (gst_rate / 100)
    return round(amount, 2), round(gst, 2), round(amount + gst, 2)

print(calculate_gst(1000))


(1000, 180.0, 1180.0)


Q47. Write a RECURSIVE function `power(base, exp)` that computes base raised to exp, WITHOUT
using the `**` operator and WITHOUT using `pow()`. Handle exp = 0 (return 1) and negative exp
(return 1/power(base, -exp)). Test with: power(2, 10), power(5, 0), power(3, -2).

In [43]:
def power(base, exp):
    if exp == 0: return 1
    if exp < 0: return 1 / power(base, -exp)
    return base * power(base, exp - 1)
print(power(2, 10))

1024


Q48. Identity Matrix Manipulations. Using NumPy: (a) create a 5×5 identity matrix using np.eye(), (b)
multiply every element by 10, (c) transpose it (yes, it looks the same, explain in a comment WHY
transpose of an identity is itself), (d) compute the sum of diagonal elements, (e) compute the sum of
all elements. Print each step.

In [44]:
import numpy as np
eye = np.eye(5)                  # (a)
eye_10 = eye * 10                 # (b)
trans = eye_10.T                  # (c) Transpose equals itself because symmetric (M[i,j] == M[j,i])
diag_sum = np.trace(eye_10)       # (d) 50.0
total_sum = eye_10.sum()          # (e) 50.0
print(eye, eye_10, trans, diag_sum, total_sum, sep="\n")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
50.0
50.0


Q49. Zomato Weekly Sales Analytics. Create a NumPy array of 7-day Zomato Bengaluru sales (in ₹):
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
[Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
Without using loops, compute and print:
(a) Total weekly sales
(b) Daily average
(c) The day (Mon/Tue/...) with maximum sales
(d) Number of days with sales above the weekly average
(e) Percentage growth from Monday to Sunday
(f) An array of day-on-day % changes (length 6)

In [45]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

print("Total:", sales.sum())
print("Average:", sales.mean())
print("Max day:", days[sales.argmax()])
print("Days > Avg:", (sales > sales.mean()).sum())
print("Mon->Sun growth %:", ((sales[-1] - sales[0]) / sales[0]) * 100)
print("DoD % change:", np.diff(sales) / sales[:-1] * 100)

Total: 150200
Average: 21457.14285714286
Max day: Sat
Days > Avg: 3
Mon->Sun growth %: 136.66666666666666
DoD % change: [ 54.16666667 -23.24324324  55.63380282 -10.40723982  77.77777778
 -19.31818182]


Q50. The Border Pattern Challenge – NO explicit loops. Create a 5×5 NumPy array where the BORDER
is 1 and the INTERIOR is 0. Output should look like:

[[1 1 1 1 1]

[1 0 0 0 1]

[1 0 0 0 1]

[1 0 0 0 1]

[1 1 1 1 1]]

Constraint: You may use np.ones(), np.zeros(), and slicing, but NO `for`, NO `while`, NO list comprehension. Only
NumPy operations.

In [46]:
import numpy as np
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
